-- ============================================================
-- Sentinel Agent Tables
-- Run this in Supabase SQL Editor (once)
-- ============================================================

-- Sentinel triage results (one row per Swift file, replaced each run)
CREATE TABLE IF NOT EXISTS triage_results (
    id              BIGSERIAL PRIMARY KEY,
    file_name       TEXT NOT NULL,
    file_path       TEXT,
    feature         TEXT,
    signal_category TEXT,
    zs_risk_level   TEXT,          -- High / Medium / Low  (intrinsic zero-shot)
    effective_risk  TEXT,          -- High / Medium / Low / No Impact (bulletin-backed)
    max_sim_score   FLOAT,
    bulletin_count  INT DEFAULT 0,
    top_bulletin_preview TEXT,
    run_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_triage_file_name ON triage_results (file_name);
CREATE INDEX IF NOT EXISTS idx_triage_effective_risk ON triage_results (effective_risk);


-- Risk history (append-only — one row per file per agent run)
CREATE TABLE IF NOT EXISTS risk_history (
    id              BIGSERIAL PRIMARY KEY,
    file_name       TEXT NOT NULL,
    effective_risk  TEXT,
    zs_risk_level   TEXT,
    max_sim_score   FLOAT,
    bulletin_count  INT DEFAULT 0,
    run_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_history_file_run ON risk_history (file_name, run_at DESC);


-- Risk alerts generated by the Coordinator
CREATE TABLE IF NOT EXISTS risk_alerts (
    id              BIGSERIAL PRIMARY KEY,
    alert_type      TEXT NOT NULL,  -- escalation | de-escalation | trending | coverage | cluster
    severity        TEXT NOT NULL,  -- high | medium | low | info
    file_name       TEXT,           -- null for cluster-level alerts
    cluster         TEXT,           -- signal_category name
    message         TEXT,
    previous_value  TEXT,
    current_value   TEXT,
    run_at          TIMESTAMPTZ DEFAULT NOW(),
    acknowledged    BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_alerts_severity ON risk_alerts (severity);
CREATE INDEX IF NOT EXISTS idx_alerts_acknowledged ON risk_alerts (acknowledged);
CREATE INDEX IF NOT EXISTS idx_alerts_run_at ON risk_alerts (run_at DESC);
