#!/usr/bin/env python3
import os
import json
import re
from pathlib import Path
from typing import List
from openai import OpenAI

# ========= CONFIG =========

USE_MOCK = False
LIMIT_FILES = 1
SOURCE_DIR = "external/fingerprintjs/src/sources"
OUT_JSONL = "data/fingerprint_summaries.jsonl"
CHUNK_TOKEN_THRESHOLD = 128

# Use the team’s current chat/instruct model here
MODEL_NAME = "meta/llama-3.1-8b-instruct"

# ==========================


def count_tokens_rough(text: str) -> int:
    words = re.findall(r"\S+", text)
    return int(len(words) / 0.75) if words else 0


def split_chunks(text: str, threshold: int) -> List[str]:
    text = text.strip()
    if not text:
        return []

    parts = [p.strip() for p in re.split(r"\n\s*\n+", text) if p.strip()]
    if len(parts) == 1:
        parts = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if s.strip()]

    chunks = []
    cur = []
    cur_tok = 0

    for p in parts:
        pt = count_tokens_rough(p)
        if cur_tok + pt <= threshold:
            cur.append(p)
            cur_tok += pt
        else:
            if cur:
                chunks.append("\n\n".join(cur))
            cur = [p]
            cur_tok = pt

    if cur:
        chunks.append("\n\n".join(cur))

    return chunks


def iter_ts_files(source_dir: Path):
    for fp in sorted(source_dir.glob("*.ts")):
        name = fp.name
        if name.endswith(".test.ts") or name.endswith(".spec.ts") or name == "index.ts":
            continue
        yield fp


def build_prompt(file_path: str, code: str) -> str:
    return f"""
You are analyzing advanced browser fingerprinting source code.

Return ONLY valid JSON with fields:
- purpose
- logic
- fingerprinting_value
- signals (array of snake_case keywords)

Be technically precise.

File path: {file_path}

Code:
{code}
"""


def call_llm(prompt: str, client: OpenAI):
    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {"role": "system", "content": "Return ONLY valid JSON."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.2,
        max_tokens=800
    )

    output = response.choices[0].message.content.strip()

    try:
        json_start = output.find("{")
        json_end = output.rfind("}") + 1
        json_str = output[json_start:json_end]
        return json.loads(json_str)
    except Exception:
        print("⚠️ Model did not return valid JSON.")
        return {
            "purpose": output[:200],
            "logic": output,
            "fingerprinting_value": "Generated by NVIDIA-hosted model.",
            "signals": []
        }


def main():
    api_key = os.getenv("NVIDIA_API_KEY")
    if not api_key:
        raise RuntimeError("Missing NVIDIA_API_KEY")

    client = OpenAI(
        base_url="https://integrate.api.nvidia.com/v1",
        api_key=api_key
    )

    source_path = Path(SOURCE_DIR)
    output_path = Path(OUT_JSONL)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    files = list(iter_ts_files(source_path))[:LIMIT_FILES]
    print(f"Found {len(files)} TS files (limited).")

    with output_path.open("w", encoding="utf-8") as f:
        for fp in files:
            code = fp.read_text(encoding="utf-8", errors="ignore")
            rel_path = str(fp)

            prompt = build_prompt(rel_path, code)
            data = call_llm(prompt, client)

            combined_text = (
                f"Purpose: {data.get('purpose','')}\n\n"
                f"Logic: {data.get('logic','')}\n\n"
                f"Fingerprinting value: {data.get('fingerprinting_value','')}\n\n"
                f"Signals: {', '.join(data.get('signals', []))}"
            )

            token_est = count_tokens_rough(combined_text)

            if token_est > CHUNK_TOKEN_THRESHOLD:
                chunks = split_chunks(combined_text, CHUNK_TOKEN_THRESHOLD)
            else:
                chunks = [combined_text]

            record = {
                "file_path": rel_path,
                "purpose": data.get("purpose"),
                "logic": data.get("logic"),
                "fingerprinting_value": data.get("fingerprinting_value"),
                "signals": data.get("signals"),
                "token_estimate": token_est,
                "chunks": chunks,
                "mock_mode": USE_MOCK,
                "model_name": MODEL_NAME
            }

            f.write(json.dumps(record, ensure_ascii=False) + "\n")
            print(f"Processed: {fp.name} | tokens≈{token_est} | chunks={len(chunks)}")

    print("\n✅ Ingestion complete.")
    print(f"Output written to: {OUT_JSONL}")


if __name__ == "__main__":
    main()